/** Mensajes de error/estado del servidor, bilingües. `idioma` es 'es' (por defecto) o 'en'. */
const TABLA = {
  es: {
    faltanDatos: 'Faltan mediaType o dataBase64 en la petición.',
    tipoNoAdmitido: (mediaType) => `Tipo de archivo no admitido: ${mediaType}. Usa PDF, PNG, JPG, WebP o GIF.`,
    archivoDemasiadoGrande: 'El archivo supera el límite de 32 MB.',
    faltaClaveQueProbar: 'No hay ninguna clave que probar: introduce una en Ajustes.',
    claveInvalida: 'Clave inválida o revocada.',
    noConectaApi: 'No se pudo conectar con la API de Claude.',
    errorProbandoConexion: 'Error probando la conexión.',
    credencialesInvalidas: 'Credenciales de la API inválidas. Revisa la clave en Ajustes (o ANTHROPIC_API_KEY en el servidor).',
    limitePeticiones: 'Límite de peticiones alcanzado. Espera unos segundos y reintenta.',
    noConectaApiRed: 'No se pudo conectar con la API de Claude. Comprueba la red.',
    errorApi: (status, msg) => `Error de la API (${status}): ${msg}`,
    errorInesperado: 'Error inesperado analizando el plano.',
    formatoInesperado: 'La extracción enviada no tiene el formato esperado.',
    noGuardoFeedback: 'No se pudo guardar el feedback.',
    noCalculoEstadisticas: 'No se pudieron calcular las estadísticas.',
    noGuardoConfig: 'No se pudo guardar la configuración.',
    proveedorDesconocido: (p) => `Proveedor desconocido: ${p}`,
    modeloRechazo: 'El modelo rechazó procesar este documento.',
    noInterpretoRespuesta: 'No se pudo interpretar la respuesta del modelo. Vuelve a intentarlo.',
    indicaModelo: 'Indica el modelo a usar en Ajustes (debe tener visión).',
    proveedorSinPdf: 'Este proveedor no admite PDF: sube una imagen (PNG/JPG) del plano o cambia a Anthropic o Google Gemini en Ajustes.',
    geminiNecesitaClave: 'Google Gemini necesita una clave de API (gratuita en aistudio.google.com).',
    jsonNoCumpleEsquema: (detalle) => `El modelo devolvió un JSON que no cumple el esquema (${detalle}). Prueba con un modelo con visión más capaz o cambia de proveedor.`,
    valoresDescartados: (detalle) =>
      `El modelo devolvió valores no interpretables que se han descartado (${detalle}). Revísalos en el plano.`,
    faltaUrlBase: 'Este proveedor necesita una URL base: configúrala en Ajustes.',
    urlNoValida: (url) => `URL base no válida: ${url}`,
    credencialesRechazadas: 'El proveedor rechazó las credenciales: revisa la clave en Ajustes.',
    modeloONoEncontrado: (detalle) => `El proveedor no encuentra el modelo o la ruta (404). ${detalle ?? ''}`.trim(),
    limiteProveedor: 'Límite de peticiones del proveedor alcanzado; espera y reintenta.',
    errorProveedorGenerico: (status, detalle) => `Error ${status} del proveedor${detalle ? `: ${detalle}` : '.'}`,
    noConectaUrl: (url) => `No se pudo conectar con ${url}. ¿Está el servidor en marcha y accesible?`,
    respuestaSinJson: 'La respuesta del modelo no contiene un objeto JSON.',
    respuestaVacia: 'El proveedor devolvió una respuesta vacía.',
    geminiRespuestaVacia: 'Gemini devolvió una respuesta vacía (puede ser un bloqueo de seguridad).',
  },
  en: {
    faltanDatos: 'Missing mediaType or dataBase64 in the request.',
    tipoNoAdmitido: (mediaType) => `Unsupported file type: ${mediaType}. Use PDF, PNG, JPG, WebP or GIF.`,
    archivoDemasiadoGrande: 'The file exceeds the 32 MB limit.',
    faltaClaveQueProbar: 'There is no key to test: enter one in Settings.',
    claveInvalida: 'Invalid or revoked key.',
    noConectaApi: 'Could not connect to the Claude API.',
    errorProbandoConexion: 'Error testing the connection.',
    credencialesInvalidas: 'Invalid API credentials. Check the key in Settings (or ANTHROPIC_API_KEY on the server).',
    limitePeticiones: 'Rate limit reached. Wait a few seconds and retry.',
    noConectaApiRed: 'Could not connect to the Claude API. Check your network.',
    errorApi: (status, msg) => `API error (${status}): ${msg}`,
    errorInesperado: 'Unexpected error analyzing the drawing.',
    formatoInesperado: 'The submitted extraction does not have the expected format.',
    noGuardoFeedback: 'Could not save the feedback.',
    noCalculoEstadisticas: 'Could not compute the statistics.',
    noGuardoConfig: 'Could not save the configuration.',
    proveedorDesconocido: (p) => `Unknown provider: ${p}`,
    modeloRechazo: 'The model refused to process this document.',
    noInterpretoRespuesta: 'Could not parse the model\'s response. Please try again.',
    indicaModelo: 'Specify the model to use in Settings (it must support vision).',
    proveedorSinPdf: 'This provider does not support PDF: upload an image (PNG/JPG) of the drawing or switch to Anthropic or Google Gemini in Settings.',
    geminiNecesitaClave: 'Google Gemini needs an API key (free at aistudio.google.com).',
    jsonNoCumpleEsquema: (detalle) => `The model returned JSON that does not match the schema (${detalle}). Try a more capable vision model or switch providers.`,
    valoresDescartados: (detalle) =>
      `The model returned values that could not be interpreted and were discarded (${detalle}). Check them on the drawing.`,
    faltaUrlBase: 'This provider needs a base URL: configure it in Settings.',
    urlNoValida: (url) => `Invalid base URL: ${url}`,
    credencialesRechazadas: 'The provider rejected the credentials: check the key in Settings.',
    modeloONoEncontrado: (detalle) => `The provider could not find the model or route (404). ${detalle ?? ''}`.trim(),
    limiteProveedor: 'Provider rate limit reached; wait and retry.',
    errorProveedorGenerico: (status, detalle) => `Provider error ${status}${detalle ? `: ${detalle}` : '.'}`,
    noConectaUrl: (url) => `Could not connect to ${url}. Is the server running and reachable?`,
    respuestaSinJson: 'The model\'s response does not contain a JSON object.',
    respuestaVacia: 'The provider returned an empty response.',
    geminiRespuestaVacia: 'Gemini returned an empty response (it may have been safety-blocked).',
  },
};

export function mensajes(idioma) {
  return TABLA[idioma] === undefined ? TABLA.es : TABLA[idioma];
}
